### PR TITLE
Cmakeify

### PR DESCRIPTION
**Pull request by zaufi**
The project become more and more complex (and crossplatform)... it is time to introduce more reliable (and portable) way to build it ;-)

In this branch I've done a preliminary CMake'fication:
* platform depended files related to build process has been deleted
* tests are integrated into CTest
* CppUnit/GTest/Boost are optional (will be found at build time) -- you still may build the package having just some of this libs...

TODO
* produce package(s) using CPack

Also I have solution for boost 1.59 which has breaking changes in UTF lib... Going to add it soon...

### CODE REVIEW

**Comment by zaufi** [comment]
here is a little build HowTo:

    zaufi@gentop〉/work/GitHub/teamcity-cpp〉git:cmakeify〉cd build
    zaufi@gentop〉…/GitHub/teamcity-cpp/build〉git:cmakeify〉mkdir debug && cd debug
    zaufi@gentop〉…/teamcity-cpp/build/debug〉git:cmakeify〉empty dir〉cmake -DBOOST_ROOT=/usr/local  ../..
    -- The CXX compiler identification is GNU 4.9.3
    -- Check for working CXX compiler: /usr/lib/outproc/bin/c++ -- works
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features - done
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   unit_test_framework
    -- Found GTest: /usr/lib64/libgtest.so  
    -- Found CPPUNIT: -L/usr/lib64 -lcppunit -ldl (found version "1.13.2") 
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /work/GitHub/teamcity-cpp/build/debug

    zaufi@gentop〉…/teamcity-cpp/build/debug〉default〉pfx: /usr/local〉git:cmakeify〉make
    Scanning dependencies of target common
    [  9%] Building CXX object common/CMakeFiles/common.dir/teamcity_messages.cpp.o
    [  9%] Built target common
    Scanning dependencies of target boost_test
    [ 18%] Building CXX object boost/CMakeFiles/boost_test.dir/boost_test.cpp.o
    [ 27%] Building CXX object boost/CMakeFiles/boost_test.dir/teamcity_boost.cpp.o
    [ 36%] Building CXX object boost/CMakeFiles/boost_test.dir/__/common/teamcity_messages.cpp.o
    [ 45%] Linking CXX executable boost_test
    [ 45%] Built target boost_test
    Scanning dependencies of target gtest_test
    [ 54%] Building CXX object gtest/CMakeFiles/gtest_test.dir/gtest_test.cpp.o
    [ 63%] Building CXX object gtest/CMakeFiles/gtest_test.dir/teamcity_gtest.cpp.o
    [ 72%] Linking CXX executable gtest_test
    [ 72%] Built target gtest_test
    Scanning dependencies of target cppunit_test
    [ 81%] Building CXX object cppunit/CMakeFiles/cppunit_test.dir/cppunit_test.cpp.o
    [ 90%] Building CXX object cppunit/CMakeFiles/cppunit_test.dir/teamcity_cppunit.cpp.o
    [100%] Linking CXX executable cppunit_test
    [100%] Built target cppunit_test

    zaufi@gentop〉…/teamcity-cpp/build/debug〉default〉pfx: /usr/local〉git:cmakeify〉make test
    Running tests...
    Test project /work/GitHub/teamcity-cpp/build/debug
        Start 1: boost_test
    1/6 Test #1: boost_test .......................   Passed    0.06 sec
        Start 2: boost_test_flowid
    2/6 Test #2: boost_test_flowid ................   Passed    0.06 sec
        Start 3: gtest_test
    3/6 Test #3: gtest_test .......................   Passed    0.06 sec
        Start 4: gtest_test_flowid
    4/6 Test #4: gtest_test_flowid ................   Passed    0.06 sec
        Start 5: cppunit_test
    5/6 Test #5: cppunit_test .....................   Passed    0.06 sec
        Start 6: cppunit_test_flowid
    6/6 Test #6: cppunit_test_flowid ..............   Passed    0.06 sec

    100% tests passed, 0 tests failed out of 6

    Total Test time (real) =   0.37 sec

**Comment by shalupov** [comment]
Thank you! Please rebase it against current master and I'll merge it

**Comment by zaufi** [comment]
Ok, I've done w/ preliminary CMake'ification and packaging. To build "packages" one may use `make package` command. It'll produce archives w/ content similar what it was before cmake'ification.

**Comment by zaufi** [comment]
TODO
* make distribution CMake firendly -- i.e. provide `teamcity-<COMP>-config.cmake` file along w/ sources, so CMake based projects may integrate it naturally…

**Comment by shalupov** [comment]
Is it possible to relax cmake requirement to 2.8? Ubuntu trusty has it as default: http://packages.ubuntu.com/trusty/cmake

Also I tried to fix build on travis (& cmake 2.8) and it fails badly: https://travis-ci.org/JetBrains/teamcity-cpp/jobs/85932767

Please, help

**Pull request merged**
